#!/usr/bin/env python3
"""AZ Law Now redirect generator.

Reads the content-plan JSON and emits a netlify.toml-compatible [[redirects]]
block for every 301-merge candidate. Output is a fenced markdown file you
review, then paste into `netlify.toml`.

Inputs:
  data/research/content-plan-{date}.json (latest)
  netlify.toml                            (read existing redirects to skip dupes)

Output:
  data/research/proposed-redirects-{date}.md
  data/research/proposed-redirects-{date}.toml
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RESEARCH_DIR = ROOT / "data" / "research"
NETLIFY = ROOT / "netlify.toml"
SITE = "https://azlawnow.com"


def latest_plan() -> Path:
    files = sorted(RESEARCH_DIR.glob("content-plan-*.json"))
    if not files:
        sys.exit("No content-plan found. Run plan-content.py first.")
    return files[-1]


def existing_redirects() -> set[str]:
    """Parse netlify.toml for existing `from` paths to avoid duplicates."""
    paths: set[str] = set()
    if not NETLIFY.exists():
        return paths
    text = NETLIFY.read_text()
    for m in re.finditer(r'from\s*=\s*["\']([^"\']+)["\']', text):
        paths.add(m.group(1))
    return paths


def to_path(url: str) -> str:
    p = url.replace(SITE, "")
    if not p.startswith("/"):
        p = "/" + p
    return p


def main() -> None:
    plan_path = latest_plan()
    print(f"Reading {plan_path.relative_to(ROOT)}")
    plan = json.loads(plan_path.read_text())

    merges = plan.get("by_action", {}).get("301-merge", [])
    if not merges:
        sys.exit("No 301-merge candidates in plan.")

    # Dedupe by (from, to)
    seen = set()
    unique = []
    for p in merges:
        rec = p["recommendation"]
        f = rec.get("from_url", "")
        t = rec.get("to_url", "")
        key = (f, t)
        if key in seen:
            continue
        seen.add(key)
        # carry priority info from the highest-volume occurrence
        p["_volume"] = p.get("search_volume", 0)
        unique.append(p)
    unique.sort(key=lambda p: -p["_volume"])

    existing = existing_redirects()

    today = datetime.now().strftime("%Y-%m-%d")
    md_path = RESEARCH_DIR / f"proposed-redirects-{today}.md"
    toml_path = RESEARCH_DIR / f"proposed-redirects-{today}.toml"

    md = [
        f"# Proposed 301 Redirects — {today}",
        "",
        f"Source: `{plan_path.relative_to(ROOT)}`",
        f"Existing redirects in `netlify.toml`: **{len(existing)}** (skipped)",
        "",
        "Review each row. When ready, copy the TOML block from",
        f"`{toml_path.relative_to(ROOT)}` into `netlify.toml` at the bottom",
        "of the `[[redirects]]` section, commit, deploy.",
        "",
        "| # | Vol | Pos | Query | From → To | Status |",
        "|---:|---:|---:|---|---|---|",
    ]
    toml_lines = [
        f"# Generated by scripts/seo/build-redirects.py on {today}",
        f"# Source: {plan_path.name}",
        "",
    ]

    fresh_count = 0
    skipped_count = 0
    for i, p in enumerate(unique, 1):
        rec = p["recommendation"]
        f = to_path(rec.get("from_url", ""))
        t = to_path(rec.get("to_url", ""))
        if f in existing:
            md.append(f"| {i} | {p['_volume']} | {p['our_position'] or '—'} | "
                      f"{p['query']} | `{f}` → `{t}` | _already in netlify.toml_ |")
            skipped_count += 1
            continue
        md.append(f"| {i} | {p['_volume']} | {p['our_position'] or '—'} | "
                  f"{p['query']} | `{f}` → `{t}` | **new** |")
        toml_lines.append("[[redirects]]")
        toml_lines.append(f'  from = "{f}"')
        toml_lines.append(f'  to = "{t}"')
        toml_lines.append('  status = 301')
        toml_lines.append('  force = true')
        toml_lines.append("")
        fresh_count += 1

    md += [
        "",
        f"**Generated {fresh_count} new redirects; {skipped_count} already present.**",
        "",
        "## How to apply",
        "",
        "```bash",
        f"# Review the proposed block",
        f"cat {toml_path.relative_to(ROOT)}",
        "",
        "# Append to netlify.toml (after manual review)",
        f"cat {toml_path.relative_to(ROOT)} >> netlify.toml",
        "",
        "# Commit + deploy",
        "git add netlify.toml",
        f'git commit -m "Add {fresh_count} 301-merges for legacy flat-slug URLs"',
        "git push",
        "```",
        "",
        "After deploy, re-run `gsc-pull.ts` in 14 days to confirm impressions",
        "moved to the canonical URLs.",
    ]

    md_path.write_text("\n".join(md))
    toml_path.write_text("\n".join(toml_lines))

    print(f"\n✓ Wrote {md_path.relative_to(ROOT)}")
    print(f"✓ Wrote {toml_path.relative_to(ROOT)}")
    print(f"  {fresh_count} new redirects, {skipped_count} skipped (already in netlify.toml)")


if __name__ == "__main__":
    main()
